# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  format_listener:
    rules:
      - { path: '^/api/*', priorities: [json,html], fallback_format: json}
      - { path: '^/*', priorities: [html], fallback_format: html} #for rendering vue

  exception: true

  view:
    view_response_listener: force
    formats:
      json: true